# SST Plot update workflow

name: SST_Update
 
on:
  schedule:
    - cron: '13 13 * * 1,4'
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build: # jobname
    runs-on: windows-2019 # ubuntu-latest was having issues...
    strategy:
      matrix:
        r-version: ['4.0.2']

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: ${{ matrix.r-version }}
          
      - name: Cache R packages
        id: cache
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-shinydoc
          
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          install.packages(c("rerddap","dplyr","ggplot2","mapdata","pals","lubridate","sf"))
        shell: Rscript {0}
          
      - name: Updating SST data 
        run: |
          source('scripts/NRT_SST_Calc.R')
        shell: Rscript {0}
        
      - name: Running plots
        run: |
          source('scripts/NRT_SST_Plots_MODISA.R')
          source('scripts/NRT_SST_Plots_OI.R')
          source('scripts/NRT_SST_Plots_OI_HG.R')
          source('scripts/NRT_SST_Plots_MODISA_HG.R')
        shell: Rscript {0}
        
      - name: Commit files
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add *.png
          git add *.rds
          git commit -m "generated"
          git push 
